services:
  pixi:
    image: brightsec/pixi
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - pixidb
    restart: unless-stopped
    command: ["sh", "-c", "while true; do node /usr/src/pixi/web/server.js 2>&1 || true; sleep 2; done"]

  pixidb:
    image: mongo:4.4
    restart: unless-stopped
